pipeline:
  build:
    image: androidsdk/android-30
    commands:
      - ./gradlew :app:assembleDebug
  publish:
    image: qwerty287/gitea-release-attacher:v1.1.0
    environment:
      - GITEA_RELEASE_ATTACHER_INSTANCE=https://codeberg.org
      - GITEA_RELEASE_ATTACHER_USER=qwerty287
      - GITEA_RELEASE_ATTACHER_REPO=ftpclient
      - GITEA_RELEASE_ATTACHER_REMOVE_OTHERS=1
      - GITEA_RELEASE_ATTACHER_FILENAME=debug.apk
      - GITEA_RELEASE_ATTACHER_PATH=app/build/outputs/apk/debug/app-debug.apk
    secrets: [GITEA_RELEASE_ATTACHER_TOKEN]
    when:
      event: [push, tag, deployment]